### ISSUE TITLE
Make `parseDebianVersion` return `Either` or `Maybe`

### ISSUE THREAD

**Issue by jtdaugherty** [ddssff/debian-haskell#3]
The current interface for `parseDebianVersion` requires the user to catch calls to `error`.  My request is to expose more error information and to avoid the use of `error` by returning either an `Either` value or a `Maybe` value from `parseDebianVersion`.

(Cc @travitch)

**Comment by ddssff** [comment]
Time to review "8 Ways to Report Errors in Haskell".   It looks like returning Either ParseError DebianVersion might suffice.

**Comment by ddssff** [comment]
Doing this correctly is not as easy as it sounds.

**Comment by jtdaugherty** [comment]
Really? When I look at

http://hackage.haskell.org/package/debian-3.87.2/docs/src/Debian-Version-String.html

I see that there is already an `Either` interface (via `parseDV`) that is just being covered up.

**Comment by ddssff** [comment]
I guess I will start by changing the signature of parseDebianVersion and providing the old version as parseDebianVersion'.  It only gets tricky if you try to eliminate uses of parseDebianVersion' throughout the package, especially in the relation parser.

**Comment by ddssff** [comment]
Closed by f9b531959f2d0d7a02fa2d37969a16ea783a861e
