### ISSUE TITLE
Factor out version modules into a package

### ISSUE THREAD

**Issue by jtdaugherty** [ddssff/debian-haskell#4]
I'd love to use `debian` in a project but the only thing I need is the `Debian.Version` module subtree.  However I'd prefer not to have to install the `debian` dependencies that aren't used by the `Debian.Version` modules since that increases the dependency coherence burden of my project.  Can the version-related modules be factored out into a separate package, say `debian-version`?

(Cc @travitch)

**Comment by ddssff** [comment]
I will do this

**Comment by ddssff** [comment]
Maybe I will also include the Relation type.

**Comment by ddssff** [comment]
I didn't - but someone should!   I would be very easy.
